INSERT INTO [CPILUNION].[dbo].[CTI_tb_Contrato]
           ([SidEmpresa]
           ,[SidCliente]
           ,[SidContrato]
           ,[StrContrato]
           ,[FchAlta]
           ,[FchBaja]
           ,[StrCuenta]
           ,[SidUsrAlta]
           ,[FchUsrAlta]
           ,[SidUsrModif]
           ,[FchUsrModif]
           ,[SidOferta]
           ,[NumSecContrato]
           ,[SidLineaNegocio]
           ,[Nivel]
           ,[CodigoExterno]
           ,[SidCodGestor]
           ,[SidCodSupervisor]
           ,[SidCodJefeServicio])
SELECT ct.[SidEmpresa]
      ,ct.[SidCliente]
      ,ct.[SidContrato]
      ,ct.[StrContrato]
      ,ct.[FchAlta]
      ,ct.[FchBaja]
      ,ct.[StrCuenta]
      ,ct.[SidUsrAlta]
      ,ct.[FchUsrAlta]
      ,ct.[SidUsrModif]
      ,ct.[FchUsrModif]
      ,ct.[SidOferta]
      ,ct.[NumSecContrato]
      ,ct.[SidLineaNegocio]
      ,ct.[Nivel]
      ,ct.[CodigoExterno]
      ,ct.[SidCodGestor]
      ,ct.[SidCodSupervisor]
      ,ct.[SidCodJefeServicio]
  FROM [CPILUNION].[dbo].[CPContrato] ct
  INNER JOIN [CPILUNION].[dbo].CTI_tb_Cliente cl on ct.SidEmpresa=cl.sidempresa and ct.SidCliente=cl.sidcliente
  where GETDATE() between ct.FchAlta and ISNULL(ct.fchbaja,GETDATE())


