INSERT INTO CTI_tb_PersonalContrato
(
    [NidMatricula]           ,
    [IdContrato]             ,
    [SidEmpresa]             ,
    [SidTipoContrato]        ,
    [FchAlta]                ,
    [FchBaja]                ,
    [SidConvenio]            ,
    [BolNominaProrrateada]   ,
    [NidCentroTrabajo]       ,
    [NumPorcentajeIRPF]      ,
    [FchAntiguedad]          ,
    [SidMotivoBaja]          ,
    [SidUsrAlta]             ,
    [FchUsrAlta]             ,
    [SidUsrModif]            ,
    [FchUsrModif]            ,
    [Secuencial]             ,
    [BolFiniquitado]         ,
    [Id]                     ,
    [NidOcupacion]           ,
    [StrCCC]                 ,
    [SidFormaPagoNomina]     ,
    [bolprovisional]         ,
    [BolEntregaMaterial]     ,
    [BolCotiza]              ,
    [StrIBAN]                ,
    [StrBIC]                 ,
    [SidRegimen]             ,
    [BolFirmaHC]             ,
    [NumDiasPreaviso]        ,
    [StrModalidadCotizacion] ,
    [FchFinVacaciones]       ,
    [StrCampoConfigurable1]  ,
    [StrCampoConfigurable2]  ,
    [StrCampoConfigurable3]  ,
    [StrCampoConfigurable4]  ,
    [StrCampoConfigurable5]  ,
    [StrPreaviso]            ,
    [AfiAlta]                ,
    [AfiBaja]                ,
    [CodigoEnlace]           ,
    [NidTipoAntiguedad]      ,
    [Estado] 
)

SELECT
   pc.[NidMatricula]           ,
   pc.[IdContrato]             ,
   pc.[SidEmpresa]             ,
   pc.[SidTipoContrato]        ,
   pc.[FchAlta]                ,
   pc.[FchBaja]                ,
   pc.[SidConvenio]            ,
   pc.[BolNominaProrrateada]   ,
   pc.[NidCentroTrabajo]       ,
   pc.[NumPorcentajeIRPF]      ,
   pc.[FchAntiguedad]          ,
   pc.[SidMotivoBaja]          ,
   pc.[SidUsrAlta]             ,
   pc.[FchUsrAlta]             ,
   pc.[SidUsrModif]            ,
   pc.[FchUsrModif]            ,
   pc.[Secuencial]             ,
   pc.[BolFiniquitado]         ,
   pc.[Id]                     ,
   pc.[NidOcupacion]           ,
   pc.[StrCCC]                 ,
   pc.[SidFormaPagoNomina]     ,
   pc.[bolprovisional]         ,
   pc.[BolEntregaMaterial]     ,
   pc.[BolCotiza]              ,
   pc.[StrIBAN]                ,
   pc.[StrBIC]                 ,
   pc.[SidRegimen]             ,
   pc.[BolFirmaHC]             ,
   pc.[NumDiasPreaviso]        ,
   pc.[StrModalidadCotizacion] ,
   pc.[FchFinVacaciones]       ,
   pc.[StrCampoConfigurable1]  ,
   pc.[StrCampoConfigurable2]  ,
   pc.[StrCampoConfigurable3]  ,
   pc.[StrCampoConfigurable4]  ,
   pc.[StrCampoConfigurable5]  ,
   pc.[StrPreaviso]            ,
   pc.[AfiAlta]                ,
   pc.[AfiBaja]                ,
   pc.[CodigoEnlace]           ,
   pc.[NidTipoAntiguedad]      ,
   ('N')

FROM CPPersonalContrato pc
INNER JOIN CPPersonal p on pc.nidmatricula = p.nidmatricula
