USE [CPILUNION]
GO

CREATE TABLE [dbo].[CTI_tb_Personal] (
    [NidMatricula]             NUMERIC (11)    DEFAULT ((0)) NOT NULL,
    [StrNombre]                NVARCHAR (50)   DEFAULT ('') NOT NULL,
    [StrApellido1]             NVARCHAR (50)   NOT NULL,
    [StrApellido2]             NVARCHAR (50)   NOT NULL,
    [StrDni]                   NVARCHAR (50)   DEFAULT ('') NOT NULL,
    [StrPoblacion]             NVARCHAR (50)   DEFAULT ('') NOT NULL,
    [StrProvincia]             NVARCHAR (50)   DEFAULT ('') NOT NULL,
    [StrDireccion]             NVARCHAR (100)  DEFAULT ('') NOT NULL,
    [StrCP]                    NVARCHAR (50)   DEFAULT ('') NOT NULL,
    [StrSexo]                  CHAR (1)          DEFAULT ('') NOT NULL,
    [Strfotografia]            NVARCHAR (255)    DEFAULT ('') NOT NULL,
    [StrTelefono1]             NVARCHAR (50)     DEFAULT ('') NOT NULL,
    [StrTelefono2]             NVARCHAR (50)    DEFAULT ('') NOT NULL,
    [StrTelefonoControlMovil]  NVARCHAR (15)   DEFAULT ('') NOT NULL,
    [Email]                    NVARCHAR (150)  DEFAULT ('') NOT NULL,
    [NumSS1]                   CHAR (2)        NULL,
    [NumSS2]                   CHAR (8)        NULL,
    [NumSS3]                   CHAR (2)        NULL,
    [StrCCC]                   CHAR (20)       NULL,
    [BolProvisional]           BIT               DEFAULT ((0)) NULL,
    [FchNacimiento]            DATETIME        NULL,
    [SidUsrAlta]               NVARCHAR (50)     DEFAULT ('') NOT NULL,
    [FchUsrAlta]               DATETIME          DEFAULT (getdate()) NOT NULL,
    [SidUsrModif]              NVARCHAR (50)     DEFAULT ('') NOT NULL,
    [FchUsrModif]              DATETIME        NULL,
    [SidPais]                  CHAR (3)          DEFAULT ('') NOT NULL,
    [sidMunicipio]             NCHAR (5)         DEFAULT ('') NOT NULL,
    [SidProvincia]             CHAR (2)          DEFAULT ('') NOT NULL,
    [strPais]                  NVARCHAR (50)     DEFAULT ('') NULL,
    [SidSitFamiliar]           CHAR (2)          DEFAULT ('99') NOT NULL,
    [StrDNIConyuge]            NVARCHAR (10)   NULL,
    [SidDiscapacitado]         CHAR (1)         DEFAULT ('') NOT NULL,
    [NidGradoDiscapacidad]     CHAR (3)          DEFAULT ('') NOT NULL,
    [BolMovReducida]           CHAR (1)          DEFAULT ('N') NOT NULL,
    [StrResCeMe]               CHAR (1)          DEFAULT ('N') NOT NULL,
    [SidSitLaboral]            CHAR (1)          DEFAULT ('A') NOT NULL,
    [SidMovGeografica]         CHAR (1)          DEFAULT ('N') NOT NULL,
    [SidProActLaboral]         CHAR (1)          DEFAULT ('N') NOT NULL,
    [Ts]                       ROWVERSION      NOT NULL,
    [StrRegularizaIRPF]        CHAR (2)        NULL,
    [NumPensionConyuge]        NUMERIC (18, 2) NULL,
    [NumAnualidadHijos]        NUMERIC (18, 2) NULL,
    [StrPagoVivienda]          CHAR (1)        NULL,
    [SidFormaPagoNomina]       CHAR (2)        NULL,
    [StrPagoViviendaAntes2011] CHAR (1)        NULL,
    [StrObservaciones]         NVARCHAR (1000) NULL,
    [CodigoEnlace]             NVARCHAR (100)  NULL,
    [SidNacionalidad]          CHAR (3)        NULL,
    [SidTipoDiscapacidad]      NCHAR (1)         DEFAULT ('') NULL,
    [FchDiscapacidad]          DATETIME        NULL,
    [PerImpCambioResidencia]   NVARCHAR (10)   NULL,
    [FchRevocacion]            DATETIME        NULL,
    [SidTipoIdentificador]     VARCHAR (1)       DEFAULT ('1') NOT NULL,
    [Estado]       CHAR           NOT NULL DEFAULT('N'),
    PRIMARY KEY CLUSTERED ([NidMatricula] ASC)
);



