SELECT [SidEmpresa]
      ,[SidDelegacion]
      ,[StrDelegacion]
      ,[UsoHorario]
      ,[SidPais]
      ,[SidProvincia]
      ,[SidMunicipio]
      ,[SidCP]
      ,[StrDireccion]
      ,[StrTelefono1]
      ,[StrTelefono2]
      ,[StrFax]
      ,[StrEmail]
      ,[SidUsrAlta]
      ,[FchUsrAlta]
      ,[SidUsrModif]
      ,[FchUsrModif]
      ,[Ts]
      ,[CodigoExterno]
      ,[SidGerente]
  FROM [CPILUNION].[dbo].[CTI_vi_Delegacion]
GO

